import 'dotenv/config';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import User from '../models/User';
import Book from '../models/Book';
import Borrow from '../models/Borrow';
import Reservation from '../models/Reservation';
import Fine from '../models/Fine';
import Notification from '../models/Notification';

export async function seed() {
  if (mongoose.connection.readyState !== 1) {
    const uri = process.env.MONGODB_URI!;
    await mongoose.connect(uri);
    console.log('Connected to MongoDB. Starting seed...');
  } else {
    console.log('Already connected to MongoDB. Starting seed...');
  }

  // Clear
  await Promise.all([
    User.deleteMany({}),
    Book.deleteMany({}),
    Borrow.deleteMany({}),
    Reservation.deleteMany({}),
    Fine.deleteMany({}),
    Notification.deleteMany({}),
  ]);
  console.log('Cleared existing data');

  // Users
  const passwordHash = await bcrypt.hash('Admin1234!', 12);
  const patronHash = await bcrypt.hash('Patron1234!', 12);

  const librarian = await User.create({
    email: 'librarian@libraryhub.ng',
    passwordHash,
    firstName: 'Adaeze',
    lastName: 'Okafor',
    phone: '+234-801-234-5678',
    address: '15 Marina Street, Lagos Island, Lagos',
    idType: 'StaffID',
    idNumber: 'STAFF-001',
    libraryCardNumber: 'LIB-2024-00001',
    role: 'librarian',
    isActive: true,
    favoriteCategories: ['Fiction', 'History'],
  });

  const admin = await User.create({
    email: 'admin@libraryhub.ng',
    passwordHash,
    firstName: 'Chukwuemeka',
    lastName: 'Eze',
    phone: '+234-802-345-6789',
    address: '3 Broad Street, Lagos Island, Lagos',
    idType: 'StaffID',
    idNumber: 'ADMIN-001',
    libraryCardNumber: 'LIB-2024-00002',
    role: 'admin',
    isActive: true,
    favoriteCategories: ['Technology', 'Non-Fiction'],
  });

  const patron1 = await User.create({
    email: 'patron@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Ngozi',
    lastName: 'Adeyemi',
    phone: '+234-803-456-7890',
    address: '22 Allen Avenue, Ikeja, Lagos',
    idType: 'NIN',
    idNumber: 'NIN-12345678901',
    libraryCardNumber: 'LIB-2024-00003',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Fiction', "Children's"],
    fineBalance: 0,
  });

  const patron2 = await User.create({
    email: 'emeka@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Emeka',
    lastName: 'Obi',
    phone: '+234-804-567-8901',
    address: '10 University Road, Nsukka, Enugu',
    idType: 'StudentID',
    idNumber: 'STU-2024-1234',
    libraryCardNumber: 'LIB-2024-00004',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Technology', 'Science'],
    fineBalance: 0,
  });

  const patron3 = await User.create({
    email: 'amaka@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Amaka',
    lastName: 'Nwosu',
    phone: '+234-805-678-9012',
    address: '5 GRA Road, Port Harcourt, Rivers',
    idType: 'BVN',
    idNumber: 'BVN-12345678901',
    libraryCardNumber: 'LIB-2024-00005',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Biography', 'History'],
    fineBalance: 150,
  });

  const patron4 = await User.create({
    email: 'tunde@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Tunde',
    lastName: 'Fashola',
    phone: '+234-806-789-0123',
    address: '33 Ring Road, Ibadan, Oyo',
    idType: 'NIN',
    idNumber: 'NIN-98765432101',
    libraryCardNumber: 'LIB-2024-00006',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Law', 'Business'],
    fineBalance: 0,
  });

  console.log('Users created');

  // Books
  const books = await Book.insertMany([
    // Fiction - African Literature
    {
      title: 'Things Fall Apart',
      authors: ['Chinua Achebe'],
      isbn: '9780385474542',
      publisher: 'Anchor Books',
      publicationYear: 1958,
      category: 'Fiction',
      genre: ['African Literature', 'Historical Fiction'],
      format: 'physical',
      description: 'The story of Okonkwo, a leader and local wrestling champion in Umuofia — one of a fictional group of nine villages in Nigeria, inhabited by the Igbo people.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780385474542-L.jpg',
      totalCopies: 5,
      availableCopies: 3,
      shelfLocation: 'A1-001',
      condition: 'good',
      tags: ['nigeria', 'igbo', 'colonialism', 'classic'],
      totalBorrows: 47,
    },
    {
      title: 'Half of a Yellow Sun',
      authors: ['Chimamanda Ngozi Adichie'],
      isbn: '9781400095209',
      publisher: 'Knopf',
      publicationYear: 2006,
      category: 'Fiction',
      genre: ['African Literature', 'Historical Fiction', 'War'],
      format: 'physical',
      description: 'Set in Nigeria during the 1960s, this novel follows three characters caught up in the horror of the Nigerian Civil War.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781400095209-L.jpg',
      totalCopies: 4,
      availableCopies: 2,
      shelfLocation: 'A1-002',
      condition: 'good',
      tags: ['biafra', 'civil war', 'nigeria', 'adichie'],
      totalBorrows: 38,
    },
    {
      title: 'Purple Hibiscus',
      authors: ['Chimamanda Ngozi Adichie'],
      isbn: '9781616202415',
      publisher: 'Algonquin Books',
      publicationYear: 2003,
      category: 'Fiction',
      genre: ['African Literature', 'Coming of Age'],
      format: 'physical',
      description: 'A story of family, faith, and revolution set in post-colonial Nigeria.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781616202415-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'A1-003',
      condition: 'good',
      tags: ['nigeria', 'adichie', 'family', 'religion'],
      totalBorrows: 29,
    },
    {
      title: 'The Famished Road',
      authors: ['Ben Okri'],
      isbn: '9780099554639',
      publisher: 'Vintage',
      publicationYear: 1991,
      category: 'Fiction',
      genre: ['Magical Realism', 'African Literature'],
      format: 'physical',
      description: 'The Booker Prize-winning novel following Azaro, a spirit child, in a mythical Nigerian city.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780099554639-L.jpg',
      totalCopies: 2,
      availableCopies: 1,
      shelfLocation: 'A1-004',
      condition: 'fair',
      tags: ['nigeria', 'magical realism', 'booker prize'],
      totalBorrows: 22,
    },
    {
      title: 'We Need New Names',
      authors: ['NoViolet Bulawayo'],
      isbn: '9780316230872',
      publisher: 'Little, Brown',
      publicationYear: 2013,
      category: 'Fiction',
      genre: ['African Literature', 'Immigration'],
      format: 'physical',
      description: 'The story of Darling, a young girl growing up in Zimbabwe and her journey to America.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780316230872-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'A1-005',
      condition: 'good',
      tags: ['zimbabwe', 'immigration', 'africa'],
      totalBorrows: 18,
    },
    {
      title: 'Season of Migration to the North',
      authors: ['Tayeb Salih'],
      isbn: '9780894772856',
      publisher: 'Heinemann',
      publicationYear: 1966,
      category: 'Fiction',
      genre: ['African Literature', 'Post-Colonial'],
      format: 'physical',
      description: 'A masterpiece of Arabic literature exploring the encounter between North and South.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780894772856-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'A1-006',
      condition: 'good',
      tags: ['sudan', 'arabic', 'post-colonial'],
      totalBorrows: 14,
    },
    // Non-Fiction
    {
      title: 'How Europe Underdeveloped Africa',
      authors: ['Walter Rodney'],
      isbn: '9781574780482',
      publisher: 'Howard University Press',
      publicationYear: 1972,
      category: 'Non-Fiction',
      genre: ['African History', 'Economics', 'Political Science'],
      format: 'physical',
      description: 'A seminal analysis of European colonialism and its devastating effects on African development.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781574780482-L.jpg',
      totalCopies: 3,
      availableCopies: 2,
      shelfLocation: 'B2-001',
      condition: 'good',
      tags: ['africa', 'colonialism', 'economics', 'history'],
      totalBorrows: 31,
    },
    {
      title: 'Long Walk to Freedom',
      authors: ['Nelson Mandela'],
      isbn: '9780316548182',
      publisher: 'Little, Brown',
      publicationYear: 1994,
      category: 'Biography',
      genre: ['Autobiography', 'Politics'],
      format: 'physical',
      description: 'The autobiography of Nelson Mandela, from his childhood in rural South Africa to his inauguration as president.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg',
      totalCopies: 4,
      availableCopies: 2,
      shelfLocation: 'C3-001',
      condition: 'good',
      tags: ['mandela', 'south africa', 'apartheid', 'autobiography'],
      totalBorrows: 42,
    },
    {
      title: 'Americanah',
      authors: ['Chimamanda Ngozi Adichie'],
      isbn: '9780307455925',
      publisher: 'Knopf',
      publicationYear: 2013,
      category: 'Fiction',
      genre: ['African Literature', 'Romance', 'Immigration'],
      format: 'physical',
      description: 'A searing look at race in America through the eyes of a young Nigerian woman.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780307455925-L.jpg',
      totalCopies: 4,
      availableCopies: 4,
      shelfLocation: 'A1-007',
      condition: 'good',
      tags: ['nigeria', 'america', 'race', 'adichie'],
      totalBorrows: 35,
    },
    // Technology
    {
      title: 'Clean Code',
      authors: ['Robert C. Martin'],
      isbn: '9780132350884',
      publisher: 'Prentice Hall',
      publicationYear: 2008,
      category: 'Technology',
      genre: ['Software Engineering', 'Programming'],
      format: 'physical',
      description: 'A handbook of agile software craftsmanship. Every programmer should read this book.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg',
      totalCopies: 3,
      availableCopies: 1,
      shelfLocation: 'D4-001',
      condition: 'good',
      tags: ['programming', 'software engineering', 'clean code'],
      totalBorrows: 56,
    },
    {
      title: 'The Pragmatic Programmer',
      authors: ['David Thomas', 'Andrew Hunt'],
      isbn: '9780135957059',
      publisher: 'Addison-Wesley',
      publicationYear: 2019,
      category: 'Technology',
      genre: ['Software Engineering', 'Programming'],
      format: 'physical',
      description: 'Your journey to mastery. The classic book for software developers.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'D4-002',
      condition: 'good',
      tags: ['programming', 'software engineering'],
      totalBorrows: 44,
    },
    {
      title: 'Introduction to Algorithms',
      authors: ['Thomas H. Cormen', 'Charles E. Leiserson', 'Ronald L. Rivest', 'Clifford Stein'],
      isbn: '9780262033848',
      publisher: 'MIT Press',
      publicationYear: 2009,
      category: 'Technology',
      genre: ['Computer Science', 'Algorithms'],
      format: 'physical',
      description: 'The classic reference for computer science algorithms, known as CLRS.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg',
      totalCopies: 3,
      availableCopies: 2,
      shelfLocation: 'D4-003',
      condition: 'good',
      tags: ['algorithms', 'data structures', 'computer science'],
      totalBorrows: 39,
    },
    {
      title: 'Designing Data-Intensive Applications',
      authors: ['Martin Kleppmann'],
      isbn: '9781449373320',
      publisher: "O'Reilly Media",
      publicationYear: 2017,
      category: 'Technology',
      genre: ['Database', 'Systems Design'],
      format: 'physical',
      description: 'The definitive guide to the principles, practices, and challenges of data systems.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'D4-004',
      condition: 'good',
      tags: ['databases', 'distributed systems', 'big data'],
      totalBorrows: 27,
    },
    // Science
    {
      title: 'A Brief History of Time',
      authors: ['Stephen Hawking'],
      isbn: '9780553380163',
      publisher: 'Bantam Books',
      publicationYear: 1988,
      category: 'Science',
      genre: ['Physics', 'Cosmology'],
      format: 'physical',
      description: 'From the Big Bang to black holes — a journey through space and time.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'E5-001',
      condition: 'good',
      tags: ['physics', 'cosmology', 'hawking', 'universe'],
      totalBorrows: 33,
    },
    {
      title: 'The Selfish Gene',
      authors: ['Richard Dawkins'],
      isbn: '9780198788607',
      publisher: 'Oxford University Press',
      publicationYear: 1976,
      category: 'Science',
      genre: ['Biology', 'Evolution'],
      format: 'physical',
      description: 'The classic exposition of evolutionary theory from the gene\'s point of view.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780198788607-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'E5-002',
      condition: 'good',
      tags: ['evolution', 'biology', 'genetics'],
      totalBorrows: 21,
    },
    // History
    {
      title: 'Guns, Germs, and Steel',
      authors: ['Jared Diamond'],
      isbn: '9780393317558',
      publisher: 'W. W. Norton',
      publicationYear: 1997,
      category: 'History',
      genre: ['World History', 'Anthropology'],
      format: 'physical',
      description: 'The fates of human societies — why did the West conquer the rest?',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'F6-001',
      condition: 'good',
      tags: ['history', 'civilization', 'anthropology'],
      totalBorrows: 28,
    },
    {
      title: 'Sapiens: A Brief History of Humankind',
      authors: ['Yuval Noah Harari'],
      isbn: '9780062316097',
      publisher: 'Harper',
      publicationYear: 2011,
      category: 'History',
      genre: ['World History', 'Anthropology'],
      format: 'physical',
      description: 'How Homo sapiens came to dominate the world.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
      totalCopies: 4,
      availableCopies: 3,
      shelfLocation: 'F6-002',
      condition: 'good',
      tags: ['history', 'humanity', 'evolution'],
      totalBorrows: 51,
    },
    // Children's
    {
      title: 'Eze Goes to School',
      authors: ['Onuora Nzekwu', 'Michael Crowder'],
      isbn: '9780901715432',
      publisher: 'African Universities Press',
      publicationYear: 1963,
      category: "Children's",
      genre: ['Children Fiction', 'African Literature'],
      format: 'physical',
      description: 'The classic Nigerian children\'s story about Eze\'s adventures in school.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780901715432-L.jpg',
      totalCopies: 5,
      availableCopies: 4,
      shelfLocation: 'G7-001',
      condition: 'fair',
      tags: ['children', 'nigeria', 'school', 'classic'],
      totalBorrows: 67,
    },
    {
      title: 'The Tortoise and the Birds',
      authors: ['Traditional', 'Ropo Sekoni'],
      isbn: '9789780297093',
      publisher: 'Longman Nigeria',
      publicationYear: 1985,
      category: "Children's",
      genre: ['Folk Tale', 'African Literature'],
      format: 'physical',
      description: 'Traditional African fables featuring the clever tortoise.',
      coverImage: '',
      totalCopies: 6,
      availableCopies: 5,
      shelfLocation: 'G7-002',
      condition: 'fair',
      tags: ['children', 'fables', 'africa', 'tortoise'],
      totalBorrows: 45,
    },
    {
      title: 'My First Book of African Animals',
      authors: ['Kashmira Shaik'],
      isbn: '9780799320572',
      publisher: 'Struik Publishers',
      publicationYear: 2010,
      category: "Children's",
      genre: ['Educational', 'Nature'],
      format: 'physical',
      description: 'A beautiful illustrated guide to African wildlife for young readers.',
      coverImage: '',
      totalCopies: 4,
      availableCopies: 4,
      shelfLocation: 'G7-003',
      condition: 'good',
      tags: ['children', 'animals', 'africa', 'educational'],
      totalBorrows: 32,
    },
    // Reference
    {
      title: 'Oxford English Dictionary (Concise)',
      authors: ['Oxford University Press'],
      isbn: '9780199601080',
      publisher: 'Oxford University Press',
      publicationYear: 2011,
      category: 'Reference',
      genre: ['Dictionary', 'Language'],
      format: 'physical',
      description: 'The authoritative guide to the English language.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780199601080-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'H8-001',
      condition: 'good',
      tags: ['dictionary', 'english', 'reference'],
      totalBorrows: 5,
    },
    {
      title: 'Encyclopedia of African History',
      authors: ['Kevin Shillington'],
      isbn: '9781579584542',
      publisher: 'Fitzroy Dearborn',
      publicationYear: 2005,
      category: 'Reference',
      genre: ['Encyclopedia', 'History'],
      format: 'physical',
      description: 'Comprehensive 3-volume reference work on African history.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781579584542-L.jpg',
      totalCopies: 1,
      availableCopies: 1,
      shelfLocation: 'H8-002',
      condition: 'good',
      tags: ['africa', 'history', 'encyclopedia', 'reference'],
      totalBorrows: 8,
    },
    // E-Books
    {
      title: 'We Should All Be Feminists',
      authors: ['Chimamanda Ngozi Adichie'],
      isbn: '9780525436225',
      publisher: 'Anchor Books',
      publicationYear: 2014,
      category: 'Non-Fiction',
      genre: ['Feminism', 'Essay'],
      format: 'ebook',
      description: 'A personal, eloquent essay adapted from Adichie\'s 2012 TED talk.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780525436225-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['feminism', 'adichie', 'essay', 'africa'],
      digitalUrl: 'https://archive.org/details/we-should-all-be-feminists',
      totalBorrows: 89,
    },
    {
      title: 'The Alchemist',
      authors: ['Paulo Coelho'],
      isbn: '9780062315007',
      publisher: 'HarperOne',
      publicationYear: 1988,
      category: 'Fiction',
      genre: ['Philosophical Fiction', 'Adventure'],
      format: 'ebook',
      description: 'A magical story about following your dreams.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['philosophy', 'adventure', 'dreams', 'classic'],
      digitalUrl: 'https://archive.org/details/the-alchemist-paulo-coelho',
      totalBorrows: 72,
    },
    {
      title: 'Rich Dad Poor Dad',
      authors: ['Robert T. Kiyosaki'],
      isbn: '9781612680194',
      publisher: 'Plata Publishing',
      publicationYear: 1997,
      category: 'Business',
      genre: ['Personal Finance', 'Business'],
      format: 'ebook',
      description: 'What the rich teach their kids about money that the poor and middle class do not.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['finance', 'business', 'money', 'investing'],
      digitalUrl: 'https://archive.org/details/rich-dad-poor-dad',
      totalBorrows: 93,
    },
    // Audiobooks
    {
      title: 'Atomic Habits',
      authors: ['James Clear'],
      isbn: '9780735211292',
      publisher: 'Avery',
      publicationYear: 2018,
      category: 'Non-Fiction',
      genre: ['Self-Help', 'Psychology'],
      format: 'audiobook',
      description: 'An easy and proven way to build good habits and break bad ones.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['habits', 'self-help', 'psychology', 'productivity'],
      digitalUrl: 'https://archive.org/details/atomic-habits-audiobook',
      totalBorrows: 61,
    },
    {
      title: 'Think and Grow Rich',
      authors: ['Napoleon Hill'],
      isbn: '9781585424337',
      publisher: 'Tarcher/Perigee',
      publicationYear: 1937,
      category: 'Business',
      genre: ['Self-Help', 'Business'],
      format: 'audiobook',
      description: 'The classic guide to financial success and personal achievement.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['success', 'business', 'motivation', 'classic'],
      digitalUrl: 'https://archive.org/details/think-and-grow-rich-audiobook',
      totalBorrows: 48,
    },
    // More Physical Books
    {
      title: 'The God of Small Things',
      authors: ['Arundhati Roy'],
      isbn: '9780679457312',
      publisher: 'Random House',
      publicationYear: 1997,
      category: 'Fiction',
      genre: ['Literary Fiction', 'Family Drama'],
      format: 'physical',
      description: 'Booker Prize winner — the story of forbidden love in a small Indian town.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780679457312-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'A2-001',
      condition: 'good',
      tags: ['india', 'booker prize', 'literary fiction'],
      totalBorrows: 19,
    },
    {
      title: 'Pedagogy of the Oppressed',
      authors: ['Paulo Freire'],
      isbn: '9780826412768',
      publisher: 'Continuum',
      publicationYear: 1968,
      category: 'Philosophy',
      genre: ['Education', 'Philosophy'],
      format: 'physical',
      description: 'A seminal text on critical pedagogy and liberation education.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780826412768-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'I9-001',
      condition: 'good',
      tags: ['education', 'philosophy', 'social justice'],
      totalBorrows: 16,
    },
    {
      title: 'Things I Have Withheld',
      authors: ['Kei Miller'],
      isbn: '9781786331489',
      publisher: 'Canongate',
      publicationYear: 2021,
      category: 'Non-Fiction',
      genre: ['Essays', 'Race', 'Identity'],
      format: 'physical',
      description: 'A collection of essays on race, body, and silence.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781786331489-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'B3-001',
      condition: 'good',
      tags: ['race', 'essays', 'identity', 'caribbean'],
      totalBorrows: 11,
    },
  ]);

  console.log(`Created ${books.length} books`);

  // Active borrows
  const now = new Date();
  const overdueDue = new Date(now);
  overdueDue.setDate(overdueDue.getDate() - 5);

  const nearDueDue = new Date(now);
  nearDueDue.setDate(nearDueDue.getDate() + 2);

  const normalDue = new Date(now);
  normalDue.setDate(normalDue.getDate() + 10);

  const thingsFA = books.find((b) => b.title === 'Things Fall Apart')!;
  const cleanCode = books.find((b) => b.title === 'Clean Code')!;
  const sapiens = books.find((b) => b.title === 'Sapiens: A Brief History of Humankind')!;
  const halfYellow = books.find((b) => b.title === 'Half of a Yellow Sun')!;
  const longWalk = books.find((b) => b.title === 'Long Walk to Freedom')!;

  const borrow1 = await Borrow.create({
    patronId: patron3._id,
    bookId: thingsFA._id,
    librarianId: librarian._id,
    borrowDate: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000),
    dueDate: overdueDue,
    status: 'overdue',
    conditionAtBorrow: 'good',
    fine: 250,
  });

  await Borrow.create({
    patronId: patron1._id,
    bookId: cleanCode._id,
    librarianId: librarian._id,
    borrowDate: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000),
    dueDate: nearDueDue,
    status: 'active',
    conditionAtBorrow: 'good',
  });

  await Borrow.create({
    patronId: patron2._id,
    bookId: sapiens._id,
    librarianId: librarian._id,
    borrowDate: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
    dueDate: normalDue,
    status: 'active',
    conditionAtBorrow: 'good',
  });

  // Past borrows
  await Borrow.create({
    patronId: patron1._id,
    bookId: thingsFA._id,
    librarianId: librarian._id,
    borrowDate: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000),
    dueDate: new Date(now.getTime() - 46 * 24 * 60 * 60 * 1000),
    returnDate: new Date(now.getTime() - 47 * 24 * 60 * 60 * 1000),
    status: 'returned',
    conditionAtBorrow: 'good',
    conditionAtReturn: 'good',
  });

  await Borrow.create({
    patronId: patron2._id,
    bookId: halfYellow._id,
    librarianId: librarian._id,
    borrowDate: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000),
    dueDate: new Date(now.getTime() - 31 * 24 * 60 * 60 * 1000),
    returnDate: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
    status: 'returned',
    conditionAtBorrow: 'good',
    conditionAtReturn: 'good',
  });

  // Fine for overdue
  await Fine.create({
    patronId: patron3._id,
    borrowId: borrow1._id,
    bookId: thingsFA._id,
    amount: 250,
    reason: 'overdue',
    status: 'pending',
  });

  await patron3.updateOne({ fineBalance: 250 });

  // Reservations
  await Reservation.create({
    patronId: patron4._id,
    bookId: halfYellow._id,
    status: 'pending',
    waitlistPosition: 1,
    reservedAt: new Date(),
    expiresAt: new Date(now.getTime() + 48 * 60 * 60 * 1000),
  });

  await Reservation.create({
    patronId: patron1._id,
    bookId: longWalk._id,
    status: 'ready',
    waitlistPosition: 0,
    reservedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    expiresAt: new Date(now.getTime() + 46 * 60 * 60 * 1000),
  });

  // Sample notifications
  await Notification.insertMany([
    {
      userId: patron1._id,
      type: 'reservation_ready',
      title: 'Book Ready for Pickup',
      message: '"Long Walk to Freedom" is now available for pickup. Please collect it within 48 hours.',
      relatedBookId: longWalk._id,
      isRead: false,
    },
    {
      userId: patron1._id,
      type: 'due_reminder',
      title: 'Due in 2 days',
      message: '"Clean Code" is due in 2 days. Please return or renew it on time.',
      relatedBookId: cleanCode._id,
      isRead: false,
    },
    {
      userId: patron3._id,
      type: 'overdue',
      title: 'Overdue Book',
      message: '"Things Fall Apart" is overdue. Current fine: ₦250. Please return it immediately.',
      relatedBookId: thingsFA._id,
      isRead: false,
    },
    {
      userId: patron3._id,
      type: 'fine',
      title: 'Fine Added to Your Account',
      message: 'A fine of ₦250 has been added to your account. Reason: overdue return.',
      isRead: false,
    },
  ]);

  console.log('Sample borrows, reservations, fines, and notifications created');
  console.log('\n=== SEED COMPLETE ===');
  console.log('Librarian: librarian@libraryhub.ng / Admin1234!');
  console.log('Admin:     admin@libraryhub.ng / Admin1234!');
  console.log('Patron:    patron@libraryhub.ng / Patron1234!');
  console.log('Patron:    emeka@libraryhub.ng / Patron1234!');
  console.log('Patron:    amaka@libraryhub.ng / Patron1234! (has fine)');
  console.log('Patron:    tunde@libraryhub.ng / Patron1234!');

}

if (require.main === module) {
  seed().then(() => mongoose.disconnect()).catch(console.error);
}
