import 'dotenv/config';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import User from '../models/User';
import Book from '../models/Book';
import Borrow from '../models/Borrow';
import Reservation from '../models/Reservation';
import Fine from '../models/Fine';
import Notification from '../models/Notification';

export async function seed() {
  if (mongoose.connection.readyState !== 1) {
    const uri = process.env.MONGODB_URI!;
    await mongoose.connect(uri);
    console.log('Connected to MongoDB. Starting seed...');
  } else {
    console.log('Already connected to MongoDB. Starting seed...');
  }

  await Promise.all([
    User.deleteMany({}),
    Book.deleteMany({}),
    Borrow.deleteMany({}),
    Reservation.deleteMany({}),
    Fine.deleteMany({}),
    Notification.deleteMany({}),
  ]);
  console.log('Cleared existing data');

  // ── Users ──────────────────────────────────────────────────────────────────
  const staffHash = await bcrypt.hash('Admin1234!', 12);
  const patronHash = await bcrypt.hash('Patron1234!', 12);

  // Admins
  await User.create({
    email: 'admin@libraryhub.ng',
    passwordHash: staffHash,
    firstName: 'Chukwuemeka',
    lastName: 'Eze',
    phone: '+234-802-345-6789',
    address: '3 Broad Street, Lagos Island, Lagos',
    idType: 'StaffID',
    idNumber: 'ADMIN-001',
    libraryCardNumber: 'LIB-2024-00001',
    role: 'admin',
    isActive: true,
    favoriteCategories: ['Technology', 'Non-Fiction'],
  });

  await User.create({
    email: 'director@libraryhub.ng',
    passwordHash: staffHash,
    firstName: 'Oluwaseun',
    lastName: 'Adeyemi',
    phone: '+234-803-456-7890',
    address: '12 Victoria Island, Lagos',
    idType: 'StaffID',
    idNumber: 'ADMIN-002',
    libraryCardNumber: 'LIB-2024-00002',
    role: 'admin',
    isActive: true,
    favoriteCategories: ['History', 'Biography'],
  });

  await User.create({
    email: 'manager@libraryhub.ng',
    passwordHash: staffHash,
    firstName: 'Fatima',
    lastName: 'Bello',
    phone: '+234-804-567-8901',
    address: '7 Ahmadu Bello Way, Abuja',
    idType: 'StaffID',
    idNumber: 'ADMIN-003',
    libraryCardNumber: 'LIB-2024-00003',
    role: 'admin',
    isActive: true,
    favoriteCategories: ['Philosophy', 'Arts'],
  });

  // Librarians
  const librarian1 = await User.create({
    email: 'librarian@libraryhub.ng',
    passwordHash: staffHash,
    firstName: 'Adaeze',
    lastName: 'Okafor',
    phone: '+234-801-234-5678',
    address: '15 Marina Street, Lagos Island, Lagos',
    idType: 'StaffID',
    idNumber: 'STAFF-001',
    libraryCardNumber: 'LIB-2024-00004',
    role: 'librarian',
    isActive: true,
    favoriteCategories: ['Fiction', 'History'],
  });

  await User.create({
    email: 'librarian2@libraryhub.ng',
    passwordHash: staffHash,
    firstName: 'Babatunde',
    lastName: 'Olusanya',
    phone: '+234-805-678-9012',
    address: '22 Allen Avenue, Ikeja, Lagos',
    idType: 'StaffID',
    idNumber: 'STAFF-002',
    libraryCardNumber: 'LIB-2024-00005',
    role: 'librarian',
    isActive: true,
    favoriteCategories: ['Science', 'Technology'],
  });

  await User.create({
    email: 'librarian3@libraryhub.ng',
    passwordHash: staffHash,
    firstName: 'Chidinma',
    lastName: 'Nwachukwu',
    phone: '+234-806-789-0123',
    address: '5 GRA Road, Port Harcourt, Rivers',
    idType: 'StaffID',
    idNumber: 'STAFF-003',
    libraryCardNumber: 'LIB-2024-00006',
    role: 'librarian',
    isActive: true,
    favoriteCategories: ["Children's", 'Fiction'],
  });

  // Patrons
  const patron1 = await User.create({
    email: 'patron@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Ngozi',
    lastName: 'Adeyemi',
    phone: '+234-807-890-1234',
    address: '22 Allen Avenue, Ikeja, Lagos',
    idType: 'NIN',
    idNumber: 'NIN-12345678901',
    libraryCardNumber: 'LIB-2024-00007',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Fiction', "Children's"],
    fineBalance: 0,
  });

  const patron2 = await User.create({
    email: 'emeka@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Emeka',
    lastName: 'Obi',
    phone: '+234-808-901-2345',
    address: '10 University Road, Nsukka, Enugu',
    idType: 'StudentID',
    idNumber: 'STU-2024-1234',
    libraryCardNumber: 'LIB-2024-00008',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Technology', 'Science'],
    fineBalance: 0,
  });

  const patron3 = await User.create({
    email: 'amaka@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Amaka',
    lastName: 'Nwosu',
    phone: '+234-809-012-3456',
    address: '5 GRA Road, Port Harcourt, Rivers',
    idType: 'BVN',
    idNumber: 'BVN-12345678901',
    libraryCardNumber: 'LIB-2024-00009',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Biography', 'History'],
    fineBalance: 250,
  });

  const patron4 = await User.create({
    email: 'tunde@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Tunde',
    lastName: 'Fashola',
    phone: '+234-810-123-4567',
    address: '33 Ring Road, Ibadan, Oyo',
    idType: 'NIN',
    idNumber: 'NIN-98765432101',
    libraryCardNumber: 'LIB-2024-00010',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Law', 'Business'],
    fineBalance: 0,
  });

  await User.create({
    email: 'chisom@libraryhub.ng',
    passwordHash: patronHash,
    firstName: 'Chisom',
    lastName: 'Okafor',
    phone: '+234-811-234-5678',
    address: '8 Nnamdi Azikiwe Street, Onitsha, Anambra',
    idType: 'StudentID',
    idNumber: 'STU-2024-5678',
    libraryCardNumber: 'LIB-2024-00011',
    role: 'patron',
    isActive: true,
    favoriteCategories: ['Philosophy', 'Fiction'],
    fineBalance: 0,
  });

  console.log('Users created (3 admin, 3 librarian, 5 patron)');

  // ── Books ──────────────────────────────────────────────────────────────────
  const books = await Book.insertMany([
    // ── African Literature ───────────────────────────────────────────────────
    {
      title: 'Things Fall Apart',
      authors: ['Chinua Achebe'],
      isbn: '9780385474542',
      publisher: 'Anchor Books',
      publicationYear: 1958,
      category: 'Fiction',
      genre: ['African Literature', 'Historical Fiction'],
      format: 'physical',
      description: 'The story of Okonkwo, a leader and local wrestling champion in Umuofia — one of a fictional group of nine villages in Nigeria. A landmark of world literature and the most widely read novel in modern African writing.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780385474542-L.jpg',
      totalCopies: 5,
      availableCopies: 3,
      shelfLocation: 'A1-001',
      condition: 'good',
      tags: ['nigeria', 'igbo', 'colonialism', 'classic', 'achebe'],
      totalBorrows: 47,
    },
    {
      title: 'Half of a Yellow Sun',
      authors: ['Chimamanda Ngozi Adichie'],
      isbn: '9781400095209',
      publisher: 'Knopf',
      publicationYear: 2006,
      category: 'Fiction',
      genre: ['African Literature', 'Historical Fiction', 'War'],
      format: 'physical',
      description: 'Set in Nigeria during the 1960s, this novel follows three characters caught up in the horror of the Nigerian Civil War and the bid to establish the Republic of Biafra.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781400095209-L.jpg',
      totalCopies: 4,
      availableCopies: 2,
      shelfLocation: 'A1-002',
      condition: 'good',
      tags: ['biafra', 'civil war', 'nigeria', 'adichie'],
      totalBorrows: 38,
    },
    {
      title: 'Purple Hibiscus',
      authors: ['Chimamanda Ngozi Adichie'],
      isbn: '9781616202415',
      publisher: 'Algonquin Books',
      publicationYear: 2003,
      category: 'Fiction',
      genre: ['African Literature', 'Coming of Age'],
      format: 'physical',
      description: 'A story of family, faith, and revolution set in post-colonial Nigeria, following fifteen-year-old Kambili whose sheltered life is shaken when she visits her aunt.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781616202415-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'A1-003',
      condition: 'good',
      tags: ['nigeria', 'adichie', 'family', 'religion'],
      totalBorrows: 29,
    },
    {
      title: 'Americanah',
      authors: ['Chimamanda Ngozi Adichie'],
      isbn: '9780307455925',
      publisher: 'Knopf',
      publicationYear: 2013,
      category: 'Fiction',
      genre: ['African Literature', 'Romance', 'Immigration'],
      format: 'physical',
      description: 'A searing, witty look at race in America through the eyes of a young Nigerian woman, Ifemelu, who comes to America to study.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780307455925-L.jpg',
      totalCopies: 4,
      availableCopies: 4,
      shelfLocation: 'A1-004',
      condition: 'good',
      tags: ['nigeria', 'america', 'race', 'adichie'],
      totalBorrows: 35,
    },
    {
      title: 'The Famished Road',
      authors: ['Ben Okri'],
      isbn: '9780099554639',
      publisher: 'Vintage',
      publicationYear: 1991,
      category: 'Fiction',
      genre: ['Magical Realism', 'African Literature'],
      format: 'physical',
      description: 'The Booker Prize-winning novel following Azaro, a spirit child who chooses to remain in the world of the living in a mythical Nigerian city.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780099554639-L.jpg',
      totalCopies: 2,
      availableCopies: 1,
      shelfLocation: 'A1-005',
      condition: 'fair',
      tags: ['nigeria', 'magical realism', 'booker prize', 'okri'],
      totalBorrows: 22,
    },
    {
      title: 'We Need New Names',
      authors: ['NoViolet Bulawayo'],
      isbn: '9780316230872',
      publisher: 'Little, Brown',
      publicationYear: 2013,
      category: 'Fiction',
      genre: ['African Literature', 'Immigration'],
      format: 'physical',
      description: 'The story of Darling, a young girl growing up in Zimbabwe who must navigate a new life in America while longing for home.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780316230872-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'A1-006',
      condition: 'good',
      tags: ['zimbabwe', 'immigration', 'africa'],
      totalBorrows: 18,
    },
    {
      title: 'Season of Migration to the North',
      authors: ['Tayeb Salih'],
      isbn: '9780894772856',
      publisher: 'Heinemann',
      publicationYear: 1966,
      category: 'Fiction',
      genre: ['African Literature', 'Post-Colonial'],
      format: 'physical',
      description: 'A masterpiece of Arabic and African literature exploring the violent encounter between North and South through the story of a Sudanese man educated in England.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780894772856-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'A1-007',
      condition: 'good',
      tags: ['sudan', 'arabic', 'post-colonial', 'africa'],
      totalBorrows: 14,
    },
    {
      title: 'Weep Not, Child',
      authors: ["Ngũgĩ wa Thiong'o"],
      isbn: '9780143106692',
      publisher: 'Penguin',
      publicationYear: 1964,
      category: 'Fiction',
      genre: ['African Literature', 'Historical Fiction'],
      format: 'physical',
      description: 'The first East African novel published in English. A moving story about the effects of the Mau Mau uprising on the lives of ordinary Kenyans.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780143106692-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'A1-008',
      condition: 'good',
      tags: ['kenya', 'mau mau', 'africa', 'ngugi'],
      totalBorrows: 17,
    },
    {
      title: 'So Long a Letter',
      authors: ['Mariama Bâ'],
      isbn: '9780435905552',
      publisher: 'Heinemann',
      publicationYear: 1979,
      category: 'Fiction',
      genre: ['African Literature', 'Feminism'],
      format: 'physical',
      description: 'A Senegalese woman writes to her longtime friend about the devastating changes her husband\'s second marriage has brought to her life. A landmark of African feminist literature.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780435905552-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'A1-009',
      condition: 'good',
      tags: ['senegal', 'feminism', 'africa', 'epistolary'],
      totalBorrows: 12,
    },
    // ── World Fiction ────────────────────────────────────────────────────────
    {
      title: 'The God of Small Things',
      authors: ['Arundhati Roy'],
      isbn: '9780679457312',
      publisher: 'Random House',
      publicationYear: 1997,
      category: 'Fiction',
      genre: ['Literary Fiction', 'Family Drama'],
      format: 'physical',
      description: 'Booker Prize winner — the story of forbidden love and the "Love Laws" that dictate who should be loved, and how, and how much in a small Indian town.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780679457312-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'A2-001',
      condition: 'good',
      tags: ['india', 'booker prize', 'literary fiction'],
      totalBorrows: 19,
    },
    {
      title: 'The Kite Runner',
      authors: ['Khaled Hosseini'],
      isbn: '9781594631931',
      publisher: 'Riverhead Books',
      publicationYear: 2003,
      category: 'Fiction',
      genre: ['Literary Fiction', 'Coming of Age'],
      format: 'physical',
      description: 'The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father\'s servant, set against the backdrop of tumultuous events in Afghanistan.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg',
      totalCopies: 3,
      availableCopies: 2,
      shelfLocation: 'A2-002',
      condition: 'good',
      tags: ['afghanistan', 'friendship', 'redemption'],
      totalBorrows: 33,
    },
    {
      title: 'Animal Farm',
      authors: ['George Orwell'],
      isbn: '9780451526342',
      publisher: 'Signet Classic',
      publicationYear: 1945,
      category: 'Fiction',
      genre: ['Political Satire', 'Allegorical Fiction'],
      format: 'physical',
      description: 'A farm is taken over by its overworked, mistreated animals in this political satire that remains devastatingly relevant to this day.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg',
      totalCopies: 4,
      availableCopies: 4,
      shelfLocation: 'A2-003',
      condition: 'good',
      tags: ['orwell', 'satire', 'politics', 'classic'],
      totalBorrows: 41,
    },
    {
      title: '1984',
      authors: ['George Orwell'],
      isbn: '9780451524935',
      publisher: 'Signet Classic',
      publicationYear: 1949,
      category: 'Fiction',
      genre: ['Dystopian Fiction', 'Political Fiction'],
      format: 'physical',
      description: 'A shattering dystopian masterpiece and warning about totalitarianism — Big Brother is watching you.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg',
      totalCopies: 4,
      availableCopies: 3,
      shelfLocation: 'A2-004',
      condition: 'good',
      tags: ['dystopia', 'orwell', 'totalitarianism', 'classic'],
      totalBorrows: 58,
    },
    {
      title: 'Invisible Man',
      authors: ['Ralph Ellison'],
      isbn: '9780679732761',
      publisher: 'Vintage',
      publicationYear: 1952,
      category: 'Fiction',
      genre: ['Literary Fiction', 'African American Literature'],
      format: 'physical',
      description: 'A nameless narrator tells his story of growing up Black in the American South — a groundbreaking novel about race, identity, and the African American experience.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780679732761-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'A2-005',
      condition: 'good',
      tags: ['african american', 'race', 'identity', 'classic'],
      totalBorrows: 21,
    },
    {
      title: 'Their Eyes Were Watching God',
      authors: ['Zora Neale Hurston'],
      isbn: '9780060931421',
      publisher: 'Harper Perennial',
      publicationYear: 1937,
      category: 'Fiction',
      genre: ['African American Literature', 'Romance'],
      format: 'physical',
      description: 'The timeless story of a Black woman\'s journey to find herself — lyrical, powerful, and enduring.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780060931421-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'A2-006',
      condition: 'good',
      tags: ['african american', 'hurston', 'classic', 'women'],
      totalBorrows: 16,
    },
    // ── Non-Fiction ──────────────────────────────────────────────────────────
    {
      title: 'How Europe Underdeveloped Africa',
      authors: ['Walter Rodney'],
      isbn: '9781574780482',
      publisher: 'Howard University Press',
      publicationYear: 1972,
      category: 'Non-Fiction',
      genre: ['African History', 'Economics', 'Political Science'],
      format: 'physical',
      description: 'A seminal analysis of European colonialism and its devastating effects on African development, arguing that Africa was deliberately underdeveloped.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781574780482-L.jpg',
      totalCopies: 3,
      availableCopies: 2,
      shelfLocation: 'B2-001',
      condition: 'good',
      tags: ['africa', 'colonialism', 'economics', 'history'],
      totalBorrows: 31,
    },
    {
      title: 'Things I Have Withheld',
      authors: ['Kei Miller'],
      isbn: '9781786331489',
      publisher: 'Canongate',
      publicationYear: 2021,
      category: 'Non-Fiction',
      genre: ['Essays', 'Race', 'Identity'],
      format: 'physical',
      description: 'A stunning collection of essays on race, body, and silence — asking what we do not say and why.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781786331489-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'B2-002',
      condition: 'good',
      tags: ['race', 'essays', 'identity', 'caribbean'],
      totalBorrows: 11,
    },
    {
      title: 'Thinking, Fast and Slow',
      authors: ['Daniel Kahneman'],
      isbn: '9780374533557',
      publisher: 'Farrar, Straus and Giroux',
      publicationYear: 2011,
      category: 'Non-Fiction',
      genre: ['Psychology', 'Behavioral Economics'],
      format: 'physical',
      description: 'Nobel laureate Daniel Kahneman takes readers on a groundbreaking tour of the mind through the two systems that drive the way we think.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg',
      totalCopies: 3,
      availableCopies: 2,
      shelfLocation: 'B2-003',
      condition: 'good',
      tags: ['psychology', 'behavioral economics', 'decision making'],
      totalBorrows: 44,
    },
    {
      title: 'Outliers: The Story of Success',
      authors: ['Malcolm Gladwell'],
      isbn: '9780316017930',
      publisher: 'Little, Brown',
      publicationYear: 2008,
      category: 'Non-Fiction',
      genre: ['Sociology', 'Psychology', 'Business'],
      format: 'physical',
      description: 'What makes high-achievers different? Gladwell examines the stories of outliers — the best and brightest — to argue that success is not exceptional or mysterious.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'B2-004',
      condition: 'good',
      tags: ['success', 'sociology', 'gladwell', 'achievement'],
      totalBorrows: 37,
    },
    // ── Biography ────────────────────────────────────────────────────────────
    {
      title: 'Long Walk to Freedom',
      authors: ['Nelson Mandela'],
      isbn: '9780316548182',
      publisher: 'Little, Brown',
      publicationYear: 1994,
      category: 'Biography',
      genre: ['Autobiography', 'Politics'],
      format: 'physical',
      description: 'The autobiography of Nelson Mandela, from his childhood in rural South Africa to his inauguration as the first democratically elected president.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg',
      totalCopies: 4,
      availableCopies: 2,
      shelfLocation: 'C3-001',
      condition: 'good',
      tags: ['mandela', 'south africa', 'apartheid', 'autobiography'],
      totalBorrows: 42,
    },
    {
      title: "I Know Why the Caged Bird Sings",
      authors: ['Maya Angelou'],
      isbn: '9780375507892',
      publisher: 'Random House',
      publicationYear: 1969,
      category: 'Biography',
      genre: ['Autobiography', 'Coming of Age'],
      format: 'physical',
      description: 'Maya Angelou\'s account of her early years — one of the most moving and powerful autobiographies written by a Black American woman.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780375507892-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'C3-002',
      condition: 'good',
      tags: ['angelou', 'autobiography', 'african american', 'women'],
      totalBorrows: 26,
    },
    {
      title: 'The Autobiography of Malcolm X',
      authors: ['Malcolm X', 'Alex Haley'],
      isbn: '9780345376718',
      publisher: 'Ballantine Books',
      publicationYear: 1965,
      category: 'Biography',
      genre: ['Autobiography', 'Civil Rights', 'Islam'],
      format: 'physical',
      description: 'The story of one of the most controversial and influential figures in American history — a gripping account of transformation and discovery.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780345376718-L.jpg',
      totalCopies: 3,
      availableCopies: 2,
      shelfLocation: 'C3-003',
      condition: 'good',
      tags: ['malcolm x', 'civil rights', 'islam', 'autobiography'],
      totalBorrows: 34,
    },
    // ── Technology ───────────────────────────────────────────────────────────
    {
      title: 'Clean Code',
      authors: ['Robert C. Martin'],
      isbn: '9780132350884',
      publisher: 'Prentice Hall',
      publicationYear: 2008,
      category: 'Technology',
      genre: ['Software Engineering', 'Programming'],
      format: 'physical',
      description: 'A handbook of agile software craftsmanship — describes the principles, patterns, and practices of writing clean code.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg',
      totalCopies: 3,
      availableCopies: 1,
      shelfLocation: 'D4-001',
      condition: 'good',
      tags: ['programming', 'software engineering', 'clean code'],
      totalBorrows: 56,
    },
    {
      title: 'The Pragmatic Programmer',
      authors: ['David Thomas', 'Andrew Hunt'],
      isbn: '9780135957059',
      publisher: 'Addison-Wesley',
      publicationYear: 2019,
      category: 'Technology',
      genre: ['Software Engineering', 'Programming'],
      format: 'physical',
      description: 'Your journey to mastery — timeless advice for software developers from journeyman to master.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'D4-002',
      condition: 'good',
      tags: ['programming', 'software engineering'],
      totalBorrows: 44,
    },
    {
      title: 'Introduction to Algorithms',
      authors: ['Thomas H. Cormen', 'Charles E. Leiserson', 'Ronald L. Rivest', 'Clifford Stein'],
      isbn: '9780262033848',
      publisher: 'MIT Press',
      publicationYear: 2009,
      category: 'Technology',
      genre: ['Computer Science', 'Algorithms'],
      format: 'physical',
      description: 'The classic reference for computer science algorithms, known as CLRS — comprehensive coverage of modern algorithms.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg',
      totalCopies: 3,
      availableCopies: 2,
      shelfLocation: 'D4-003',
      condition: 'good',
      tags: ['algorithms', 'data structures', 'computer science'],
      totalBorrows: 39,
    },
    {
      title: 'Designing Data-Intensive Applications',
      authors: ['Martin Kleppmann'],
      isbn: '9781449373320',
      publisher: "O'Reilly Media",
      publicationYear: 2017,
      category: 'Technology',
      genre: ['Database', 'Systems Design'],
      format: 'physical',
      description: 'The definitive guide to the principles, practices, and challenges of data systems — databases, distributed systems, and more.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'D4-004',
      condition: 'good',
      tags: ['databases', 'distributed systems', 'big data'],
      totalBorrows: 27,
    },
    // ── Science ──────────────────────────────────────────────────────────────
    {
      title: 'A Brief History of Time',
      authors: ['Stephen Hawking'],
      isbn: '9780553380163',
      publisher: 'Bantam Books',
      publicationYear: 1988,
      category: 'Science',
      genre: ['Physics', 'Cosmology'],
      format: 'physical',
      description: 'From the Big Bang to black holes — a landmark journey through space and time by the world\'s most famous physicist.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'E5-001',
      condition: 'good',
      tags: ['physics', 'cosmology', 'hawking', 'universe'],
      totalBorrows: 33,
    },
    {
      title: 'The Selfish Gene',
      authors: ['Richard Dawkins'],
      isbn: '9780198788607',
      publisher: 'Oxford University Press',
      publicationYear: 1976,
      category: 'Science',
      genre: ['Biology', 'Evolution'],
      format: 'physical',
      description: 'The classic exposition of evolutionary theory from the gene\'s point of view — a foundation text of modern biology.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780198788607-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'E5-002',
      condition: 'good',
      tags: ['evolution', 'biology', 'genetics', 'dawkins'],
      totalBorrows: 21,
    },
    {
      title: 'Cosmos',
      authors: ['Carl Sagan'],
      isbn: '9780345539434',
      publisher: 'Ballantine Books',
      publicationYear: 1980,
      category: 'Science',
      genre: ['Astronomy', 'Cosmology', 'Popular Science'],
      format: 'physical',
      description: 'Carl Sagan\'s sweeping, passionate vision of humanity\'s place in the universe — one of the best-selling science books ever published.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780345539434-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'E5-003',
      condition: 'good',
      tags: ['astronomy', 'cosmos', 'sagan', 'universe'],
      totalBorrows: 24,
    },
    // ── History ──────────────────────────────────────────────────────────────
    {
      title: 'Guns, Germs, and Steel',
      authors: ['Jared Diamond'],
      isbn: '9780393317558',
      publisher: 'W. W. Norton',
      publicationYear: 1997,
      category: 'History',
      genre: ['World History', 'Anthropology'],
      format: 'physical',
      description: 'The fates of human societies — a Pulitzer Prize-winning exploration of why some civilizations came to dominate others.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'F6-001',
      condition: 'good',
      tags: ['history', 'civilization', 'anthropology', 'diamond'],
      totalBorrows: 28,
    },
    {
      title: 'Sapiens: A Brief History of Humankind',
      authors: ['Yuval Noah Harari'],
      isbn: '9780062316097',
      publisher: 'Harper',
      publicationYear: 2011,
      category: 'History',
      genre: ['World History', 'Anthropology'],
      format: 'physical',
      description: 'How did Homo sapiens come to dominate the world? Harari surveys the entire length of human history, from the Stone Age to the age of Silicon.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
      totalCopies: 4,
      availableCopies: 3,
      shelfLocation: 'F6-002',
      condition: 'good',
      tags: ['history', 'humanity', 'evolution', 'harari'],
      totalBorrows: 51,
    },
    // ── Philosophy ───────────────────────────────────────────────────────────
    {
      title: 'Pedagogy of the Oppressed',
      authors: ['Paulo Freire'],
      isbn: '9780826412768',
      publisher: 'Continuum',
      publicationYear: 1968,
      category: 'Philosophy',
      genre: ['Education', 'Philosophy'],
      format: 'physical',
      description: 'A seminal text on critical pedagogy and liberation education — one of the most influential educational texts of the 20th century.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780826412768-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'I9-001',
      condition: 'good',
      tags: ['education', 'philosophy', 'social justice', 'freire'],
      totalBorrows: 16,
    },
    {
      title: 'African Philosophy: An Introduction',
      authors: ["Richard H. Bell"],
      isbn: '9780742508804',
      publisher: 'Rowman & Littlefield',
      publicationYear: 2002,
      category: 'Philosophy',
      genre: ['African Philosophy', 'Ethics'],
      format: 'physical',
      description: 'A comprehensive introduction to African philosophical thought, exploring concepts of personhood, community, and ethics rooted in African traditions.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780742508804-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'I9-002',
      condition: 'good',
      tags: ['african philosophy', 'ubuntu', 'ethics', 'africa'],
      totalBorrows: 9,
    },
    // ── Business ─────────────────────────────────────────────────────────────
    {
      title: 'Zero to One',
      authors: ['Peter Thiel', 'Blake Masters'],
      isbn: '9780804139021',
      publisher: 'Crown Business',
      publicationYear: 2014,
      category: 'Business',
      genre: ['Entrepreneurship', 'Technology'],
      format: 'physical',
      description: 'Notes on startups, or how to build the future — a unique perspective on innovation from one of Silicon Valley\'s most contrarian thinkers.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'J10-001',
      condition: 'good',
      tags: ['startup', 'entrepreneurship', 'thiel', 'innovation'],
      totalBorrows: 39,
    },
    {
      title: 'Business Adventures',
      authors: ['John Brooks'],
      isbn: '9781497644960',
      publisher: 'Open Road Media',
      publicationYear: 1969,
      category: 'Business',
      genre: ['Business History', 'Finance'],
      format: 'physical',
      description: 'Twelve classic tales from the world of Wall Street — Bill Gates\' and Warren Buffett\'s favorite business book.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781497644960-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'J10-002',
      condition: 'good',
      tags: ['business', 'wall street', 'finance', 'classic'],
      totalBorrows: 13,
    },
    // ── Children's ───────────────────────────────────────────────────────────
    {
      title: 'Eze Goes to School',
      authors: ['Onuora Nzekwu', 'Michael Crowder'],
      isbn: '9780901715432',
      publisher: 'African Universities Press',
      publicationYear: 1963,
      category: "Children's",
      genre: ['Children Fiction', 'African Literature'],
      format: 'physical',
      description: 'The classic Nigerian children\'s story about Eze\'s adventures in school — a beloved staple of African children\'s literature.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780901715432-L.jpg',
      totalCopies: 5,
      availableCopies: 4,
      shelfLocation: 'G7-001',
      condition: 'fair',
      tags: ['children', 'nigeria', 'school', 'classic'],
      totalBorrows: 67,
    },
    {
      title: 'The Tortoise and the Birds',
      authors: ['Traditional', 'Ropo Sekoni'],
      isbn: '9789780297093',
      publisher: 'Longman Nigeria',
      publicationYear: 1985,
      category: "Children's",
      genre: ['Folk Tale', 'African Literature'],
      format: 'physical',
      description: 'Traditional African fables featuring the clever tortoise — a treasury of West African folk wisdom for young readers.',
      coverImage: '',
      totalCopies: 6,
      availableCopies: 5,
      shelfLocation: 'G7-002',
      condition: 'fair',
      tags: ['children', 'fables', 'africa', 'tortoise'],
      totalBorrows: 45,
    },
    {
      title: 'My First Book of African Animals',
      authors: ['Kashmira Shaik'],
      isbn: '9780799320572',
      publisher: 'Struik Publishers',
      publicationYear: 2010,
      category: "Children's",
      genre: ['Educational', 'Nature'],
      format: 'physical',
      description: 'A beautifully illustrated guide to African wildlife for young readers, with full-color photographs and fascinating facts.',
      coverImage: '',
      totalCopies: 4,
      availableCopies: 4,
      shelfLocation: 'G7-003',
      condition: 'good',
      tags: ['children', 'animals', 'africa', 'educational'],
      totalBorrows: 32,
    },
    {
      title: 'Chike and the River',
      authors: ['Chinua Achebe'],
      isbn: '9780521467001',
      publisher: 'Cambridge University Press',
      publicationYear: 1966,
      category: "Children's",
      genre: ['Children Fiction', 'African Literature'],
      format: 'physical',
      description: 'A young boy from a village in eastern Nigeria dreams of crossing the great River Niger to the city of Asaba — a classic African children\'s adventure.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780521467001-L.jpg',
      totalCopies: 4,
      availableCopies: 4,
      shelfLocation: 'G7-004',
      condition: 'good',
      tags: ['children', 'nigeria', 'achebe', 'adventure'],
      totalBorrows: 28,
    },
    // ── Reference ────────────────────────────────────────────────────────────
    {
      title: 'Oxford English Dictionary (Concise)',
      authors: ['Oxford University Press'],
      isbn: '9780199601080',
      publisher: 'Oxford University Press',
      publicationYear: 2011,
      category: 'Reference',
      genre: ['Dictionary', 'Language'],
      format: 'physical',
      description: 'The authoritative guide to the English language — over 240,000 words, phrases, and definitions.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780199601080-L.jpg',
      totalCopies: 2,
      availableCopies: 2,
      shelfLocation: 'H8-001',
      condition: 'good',
      tags: ['dictionary', 'english', 'reference'],
      totalBorrows: 5,
    },
    {
      title: 'Encyclopedia of African History',
      authors: ['Kevin Shillington'],
      isbn: '9781579584542',
      publisher: 'Fitzroy Dearborn',
      publicationYear: 2005,
      category: 'Reference',
      genre: ['Encyclopedia', 'History'],
      format: 'physical',
      description: 'Comprehensive 3-volume reference work on African history from prehistoric times to the present day.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781579584542-L.jpg',
      totalCopies: 1,
      availableCopies: 1,
      shelfLocation: 'H8-002',
      condition: 'good',
      tags: ['africa', 'history', 'encyclopedia', 'reference'],
      totalBorrows: 8,
    },
    // ── Law ──────────────────────────────────────────────────────────────────
    {
      title: 'Constitution of the Federal Republic of Nigeria 1999',
      authors: ['Federal Republic of Nigeria'],
      isbn: '9789789110902',
      publisher: 'Government Press',
      publicationYear: 1999,
      category: 'Law',
      genre: ['Constitutional Law', 'Government'],
      format: 'physical',
      description: 'The Constitution of the Federal Republic of Nigeria as amended — the supreme law of the land.',
      coverImage: '',
      totalCopies: 3,
      availableCopies: 3,
      shelfLocation: 'K11-001',
      condition: 'good',
      tags: ['nigeria', 'constitution', 'law', 'government'],
      totalBorrows: 14,
    },
    // ── E-Books (Project Gutenberg / Internet Archive) ───────────────────────
    {
      title: 'Pride and Prejudice',
      authors: ['Jane Austen'],
      isbn: '9780141439518',
      publisher: 'Project Gutenberg',
      publicationYear: 1813,
      category: 'Fiction',
      genre: ['Classic Literature', 'Romance', 'Regency'],
      format: 'ebook',
      description: 'Jane Austen\'s beloved masterpiece follows the spirited Elizabeth Bennet as she navigates issues of manners, upbringing, morality, education, and marriage in early 19th-century England.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['classic', 'austen', 'romance', 'regency'],
      ebookUrl: 'https://www.gutenberg.org/files/1342/1342-h/1342-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 62,
    },
    {
      title: "Alice's Adventures in Wonderland",
      authors: ['Lewis Carroll'],
      isbn: '9780141439761',
      publisher: 'Project Gutenberg',
      publicationYear: 1865,
      category: 'Fiction',
      genre: ['Classic Literature', 'Fantasy', "Children's"],
      format: 'ebook',
      description: 'Alice falls through a rabbit hole into a fantasy world populated by peculiar and anthropomorphic creatures — the most beloved children\'s book ever written.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['classic', 'carroll', 'fantasy', 'children'],
      ebookUrl: 'https://www.gutenberg.org/files/11/11-h/11-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 55,
    },
    {
      title: 'The Picture of Dorian Gray',
      authors: ['Oscar Wilde'],
      isbn: '9780141439570',
      publisher: 'Project Gutenberg',
      publicationYear: 1890,
      category: 'Fiction',
      genre: ['Classic Literature', 'Gothic Fiction', 'Philosophical Fiction'],
      format: 'ebook',
      description: 'A young man sells his soul for eternal youth and beauty in Oscar Wilde\'s only novel — a decadent masterpiece of Victorian literature.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['wilde', 'classic', 'gothic', 'victorian'],
      ebookUrl: 'https://www.gutenberg.org/files/174/174-h/174-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 43,
    },
    {
      title: 'Frankenstein',
      authors: ['Mary Shelley'],
      isbn: '9780141439471',
      publisher: 'Project Gutenberg',
      publicationYear: 1818,
      category: 'Fiction',
      genre: ['Classic Literature', 'Gothic Fiction', 'Science Fiction'],
      format: 'ebook',
      description: 'Victor Frankenstein creates a sapient creature in an unorthodox scientific experiment — the founding text of science fiction and a meditation on what it means to be human.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780141439471-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['shelley', 'classic', 'gothic', 'science fiction'],
      ebookUrl: 'https://www.gutenberg.org/files/84/84-h/84-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 38,
    },
    {
      title: 'Moby-Dick',
      authors: ['Herman Melville'],
      isbn: '9780142437247',
      publisher: 'Project Gutenberg',
      publicationYear: 1851,
      category: 'Fiction',
      genre: ['Classic Literature', 'Adventure', 'Maritime Fiction'],
      format: 'ebook',
      description: 'Ishmael narrates the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on the white whale Moby Dick — one of the Great American Novels.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['melville', 'classic', 'adventure', 'american'],
      ebookUrl: 'https://www.gutenberg.org/files/2701/2701-h/2701-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 29,
    },
    {
      title: 'Adventures of Huckleberry Finn',
      authors: ['Mark Twain'],
      isbn: '9780142437179',
      publisher: 'Project Gutenberg',
      publicationYear: 1884,
      category: 'Fiction',
      genre: ['Classic Literature', 'Adventure', 'Satire'],
      format: 'ebook',
      description: 'Huck Finn and the runaway slave Jim journey down the Mississippi River — a satirical look at race, society, and the idea of civilization in 19th-century America.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780142437179-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['twain', 'classic', 'adventure', 'mississippi'],
      ebookUrl: 'https://www.gutenberg.org/files/76/76-h/76-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 31,
    },
    {
      title: 'Crime and Punishment',
      authors: ['Fyodor Dostoevsky'],
      isbn: '9780143058144',
      publisher: 'Project Gutenberg',
      publicationYear: 1866,
      category: 'Fiction',
      genre: ['Classic Literature', 'Psychological Fiction'],
      format: 'ebook',
      description: 'A young student murders a pawnbroker for her money, believing himself beyond conventional ethics. Dostoevsky\'s exploration of guilt and redemption is one of literature\'s greatest psychological novels.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780143058144-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['dostoevsky', 'classic', 'russian', 'psychological'],
      ebookUrl: 'https://www.gutenberg.org/files/2554/2554-h/2554-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 24,
    },
    {
      title: 'The Jungle Book',
      authors: ['Rudyard Kipling'],
      isbn: '9780142437308',
      publisher: 'Project Gutenberg',
      publicationYear: 1894,
      category: "Children's",
      genre: ['Classic Literature', 'Adventure', "Children's"],
      format: 'ebook',
      description: 'Mowgli, a boy raised by wolves in the jungles of India, learns wisdom from Baloo the bear and Bagheera the panther — a timeless classic.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780142437308-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['kipling', 'classic', 'adventure', 'children', 'india'],
      ebookUrl: 'https://www.gutenberg.org/files/236/236-h/236-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 47,
    },
    {
      title: 'The Call of the Wild',
      authors: ['Jack London'],
      isbn: '9780142437179',
      publisher: 'Project Gutenberg',
      publicationYear: 1903,
      category: 'Fiction',
      genre: ['Classic Literature', 'Adventure'],
      format: 'ebook',
      description: 'Buck, a large and powerful dog, is stolen from his comfortable home and sold into the brutal life of an Alaskan sled dog — Jack London\'s classic tale of survival.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780142437179-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['london', 'classic', 'adventure', 'alaska'],
      ebookUrl: 'https://www.gutenberg.org/files/215/215-h/215-h.htm',
      mediaType: 'gutenberg',
      totalBorrows: 22,
    },
    {
      title: 'We Should All Be Feminists',
      authors: ['Chimamanda Ngozi Adichie'],
      isbn: '9780525436225',
      publisher: 'Anchor Books',
      publicationYear: 2014,
      category: 'Non-Fiction',
      genre: ['Feminism', 'Essay'],
      format: 'ebook',
      description: 'A personal, eloquent, witty essay adapted from Adichie\'s 2012 TED talk — a global call to arms for feminism.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780525436225-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['feminism', 'adichie', 'essay', 'africa'],
      ebookUrl: 'https://archive.org/details/we-should-all-be-feminists',
      mediaType: 'archive',
      totalBorrows: 89,
    },
    {
      title: 'Rich Dad Poor Dad',
      authors: ['Robert T. Kiyosaki'],
      isbn: '9781612680194',
      publisher: 'Plata Publishing',
      publicationYear: 1997,
      category: 'Business',
      genre: ['Personal Finance', 'Business'],
      format: 'ebook',
      description: 'What the rich teach their kids about money that the poor and middle class do not. The #1 best-selling personal finance book of all time.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['finance', 'business', 'money', 'investing'],
      ebookUrl: 'https://archive.org/details/rich-dad-poor-dad',
      mediaType: 'archive',
      totalBorrows: 93,
    },
    // ── Audiobooks (LibriVox) ────────────────────────────────────────────────
    {
      title: 'The War of the Worlds',
      authors: ['H. G. Wells'],
      isbn: '9780141441030',
      publisher: 'LibriVox',
      publicationYear: 1898,
      category: 'Fiction',
      genre: ['Classic Literature', 'Science Fiction'],
      format: 'audiobook',
      description: 'Martians invade Victorian England in H.G. Wells\' classic novel — the original alien invasion story and a masterpiece of early science fiction.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780141441030-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['wells', 'classic', 'science fiction', 'aliens'],
      audiobookUrl: 'https://librivox.org/the-war-of-the-worlds-by-h-g-wells/',
      mediaType: 'librivox',
      totalBorrows: 41,
    },
    {
      title: 'Around the World in Eighty Days',
      authors: ['Jules Verne'],
      isbn: '9780140449068',
      publisher: 'LibriVox',
      publicationYear: 1872,
      category: 'Fiction',
      genre: ['Classic Literature', 'Adventure'],
      format: 'audiobook',
      description: 'The eccentric British gentleman Phileas Fogg sets out to circumnavigate the globe in eighty days after making a wager at his gentlemen\'s club.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780140449068-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['verne', 'classic', 'adventure', 'travel'],
      audiobookUrl: 'https://librivox.org/around-the-world-in-eighty-days-by-jules-verne/',
      mediaType: 'librivox',
      totalBorrows: 36,
    },
    {
      title: 'The Adventures of Sherlock Holmes',
      authors: ['Arthur Conan Doyle'],
      isbn: '9780140439076',
      publisher: 'LibriVox',
      publicationYear: 1892,
      category: 'Fiction',
      genre: ['Classic Literature', 'Mystery', 'Detective Fiction'],
      format: 'audiobook',
      description: 'Twelve stories featuring the world\'s greatest detective Sherlock Holmes and his loyal companion Dr. Watson — classic tales of logic and deduction.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780140439076-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['doyle', 'sherlock', 'mystery', 'detective', 'classic'],
      audiobookUrl: 'https://librivox.org/the-adventures-of-sherlock-holmes-by-arthur-conan-doyle-2/',
      mediaType: 'librivox',
      totalBorrows: 58,
    },
    {
      title: 'Treasure Island',
      authors: ['Robert Louis Stevenson'],
      isbn: '9780142437681',
      publisher: 'LibriVox',
      publicationYear: 1883,
      category: 'Fiction',
      genre: ['Classic Literature', 'Adventure', "Children's"],
      format: 'audiobook',
      description: 'Young Jim Hawkins stumbles upon a treasure map and sets sail to find the pirate gold on a remote island — the definitive adventure story.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780142437681-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['stevenson', 'classic', 'adventure', 'pirates'],
      audiobookUrl: 'https://librivox.org/treasure-island-by-robert-louis-stevenson-2/',
      mediaType: 'librivox',
      totalBorrows: 44,
    },
    {
      title: 'A Tale of Two Cities',
      authors: ['Charles Dickens'],
      isbn: '9780141439600',
      publisher: 'LibriVox',
      publicationYear: 1859,
      category: 'Fiction',
      genre: ['Classic Literature', 'Historical Fiction'],
      format: 'audiobook',
      description: 'Set in London and Paris before and during the French Revolution — "It was the best of times, it was the worst of times." Dickens\' most popular novel.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780141439600-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['dickens', 'classic', 'french revolution', 'historical'],
      audiobookUrl: 'https://librivox.org/a-tale-of-two-cities-by-charles-dickens/',
      mediaType: 'librivox',
      totalBorrows: 33,
    },
    {
      title: 'The Art of War',
      authors: ['Sun Tzu'],
      isbn: '9780143105855',
      publisher: 'LibriVox',
      publicationYear: -500,
      category: 'Philosophy',
      genre: ['Military Strategy', 'Philosophy', 'Classic'],
      format: 'audiobook',
      description: 'The ancient Chinese military treatise by Sun Tzu — one of the oldest and most influential texts on military strategy and tactics, still widely applied in business today.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780143105855-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['sun tzu', 'strategy', 'philosophy', 'military', 'classic'],
      audiobookUrl: 'https://librivox.org/the-art-of-war-by-sun-tzu/',
      mediaType: 'librivox',
      totalBorrows: 52,
    },
    {
      title: 'Atomic Habits',
      authors: ['James Clear'],
      isbn: '9780735211292',
      publisher: 'Avery',
      publicationYear: 2018,
      category: 'Non-Fiction',
      genre: ['Self-Help', 'Psychology', 'Productivity'],
      format: 'audiobook',
      description: 'An easy and proven way to build good habits and break bad ones — tiny changes that lead to remarkable results.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['habits', 'self-help', 'psychology', 'productivity', 'clear'],
      audiobookUrl: 'https://archive.org/details/atomic-habits-audiobook',
      mediaType: 'archive',
      totalBorrows: 61,
    },
    {
      title: 'Think and Grow Rich',
      authors: ['Napoleon Hill'],
      isbn: '9781585424337',
      publisher: 'LibriVox',
      publicationYear: 1937,
      category: 'Business',
      genre: ['Self-Help', 'Business', 'Motivation'],
      format: 'audiobook',
      description: 'The classic guide to financial success and personal achievement — one of the best-selling books of all time.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['success', 'business', 'motivation', 'classic', 'hill'],
      audiobookUrl: 'https://librivox.org/think-and-grow-rich-by-napoleon-hill/',
      mediaType: 'librivox',
      totalBorrows: 48,
    },
    {
      title: 'The Odyssey',
      authors: ['Homer', 'Samuel Butler (translator)'],
      isbn: '9780140268867',
      publisher: 'LibriVox',
      publicationYear: -800,
      category: 'Fiction',
      genre: ['Classic Literature', 'Epic Poetry', 'Mythology'],
      format: 'audiobook',
      description: 'The homeward journey of Odysseus after the fall of Troy — one of the oldest and most influential works of Western literature.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['homer', 'classic', 'greek', 'mythology', 'epic'],
      audiobookUrl: 'https://librivox.org/the-odyssey-by-homer/',
      mediaType: 'librivox',
      totalBorrows: 27,
    },
    {
      title: 'The Alchemist',
      authors: ['Paulo Coelho'],
      isbn: '9780062315007',
      publisher: 'HarperOne',
      publicationYear: 1988,
      category: 'Fiction',
      genre: ['Philosophical Fiction', 'Adventure'],
      format: 'audiobook',
      description: 'A magical story about following your dreams — a young shepherd journeys from Andalucia to Egypt in search of treasure.',
      coverImage: 'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg',
      totalCopies: 999,
      availableCopies: 999,
      condition: 'good',
      tags: ['coelho', 'philosophy', 'adventure', 'dreams', 'classic'],
      audiobookUrl: 'https://archive.org/details/the-alchemist-paulo-coelho',
      mediaType: 'archive',
      totalBorrows: 72,
    },
  ]);

  console.log(`Created ${books.length} books`);

  // ── Sample Borrows ─────────────────────────────────────────────────────────
  const now = new Date();
  const overdueDue = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000);
  const nearDueDue = new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000);
  const normalDue = new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000);

  const thingsFA = books.find((b) => b.title === 'Things Fall Apart')!;
  const cleanCode = books.find((b) => b.title === 'Clean Code')!;
  const sapiens = books.find((b) => b.title === 'Sapiens: A Brief History of Humankind')!;
  const halfYellow = books.find((b) => b.title === 'Half of a Yellow Sun')!;
  const longWalk = books.find((b) => b.title === 'Long Walk to Freedom')!;

  const borrow1 = await Borrow.create({
    patronId: patron3._id,
    bookId: thingsFA._id,
    librarianId: librarian1._id,
    borrowDate: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000),
    dueDate: overdueDue,
    status: 'overdue',
    conditionAtBorrow: 'good',
    fine: 250,
  });

  await Borrow.create({
    patronId: patron1._id,
    bookId: cleanCode._id,
    librarianId: librarian1._id,
    borrowDate: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000),
    dueDate: nearDueDue,
    status: 'active',
    conditionAtBorrow: 'good',
  });

  await Borrow.create({
    patronId: patron2._id,
    bookId: sapiens._id,
    librarianId: librarian1._id,
    borrowDate: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
    dueDate: normalDue,
    status: 'active',
    conditionAtBorrow: 'good',
  });

  await Borrow.create({
    patronId: patron1._id,
    bookId: thingsFA._id,
    librarianId: librarian1._id,
    borrowDate: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000),
    dueDate: new Date(now.getTime() - 46 * 24 * 60 * 60 * 1000),
    returnDate: new Date(now.getTime() - 47 * 24 * 60 * 60 * 1000),
    status: 'returned',
    conditionAtBorrow: 'good',
    conditionAtReturn: 'good',
  });

  await Borrow.create({
    patronId: patron2._id,
    bookId: halfYellow._id,
    librarianId: librarian1._id,
    borrowDate: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000),
    dueDate: new Date(now.getTime() - 31 * 24 * 60 * 60 * 1000),
    returnDate: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
    status: 'returned',
    conditionAtBorrow: 'good',
    conditionAtReturn: 'good',
  });

  await Fine.create({
    patronId: patron3._id,
    borrowId: borrow1._id,
    bookId: thingsFA._id,
    amount: 250,
    reason: 'overdue',
    status: 'pending',
  });

  await patron3.updateOne({ fineBalance: 250 });

  // ── Reservations ───────────────────────────────────────────────────────────
  await Reservation.create({
    patronId: patron4._id,
    bookId: halfYellow._id,
    status: 'pending',
    waitlistPosition: 1,
    reservedAt: new Date(),
    expiresAt: new Date(now.getTime() + 48 * 60 * 60 * 1000),
  });

  await Reservation.create({
    patronId: patron1._id,
    bookId: longWalk._id,
    status: 'ready',
    waitlistPosition: 0,
    reservedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    expiresAt: new Date(now.getTime() + 46 * 60 * 60 * 1000),
  });

  // ── Notifications ──────────────────────────────────────────────────────────
  await Notification.insertMany([
    {
      userId: patron1._id,
      type: 'reservation_ready',
      title: 'Book Ready for Pickup',
      message: '"Long Walk to Freedom" is now available for pickup. Please collect it within 48 hours.',
      relatedBookId: longWalk._id,
      isRead: false,
    },
    {
      userId: patron1._id,
      type: 'due_reminder',
      title: 'Due in 2 days',
      message: '"Clean Code" is due in 2 days. Please return or renew it on time.',
      relatedBookId: cleanCode._id,
      isRead: false,
    },
    {
      userId: patron3._id,
      type: 'overdue',
      title: 'Overdue Book',
      message: '"Things Fall Apart" is overdue. Current fine: ₦250. Please return it immediately.',
      relatedBookId: thingsFA._id,
      isRead: false,
    },
    {
      userId: patron3._id,
      type: 'fine',
      title: 'Fine Added to Your Account',
      message: 'A fine of ₦250 has been added to your account for the overdue return of "Things Fall Apart".',
      isRead: false,
    },
  ]);

  console.log('Borrows, reservations, fines, and notifications created');
  console.log('\n=== SEED COMPLETE ===');
  console.log(`Total books: ${books.length}`);
  console.log('── Admins ──');
  console.log('admin@libraryhub.ng      / Admin1234!');
  console.log('director@libraryhub.ng   / Admin1234!');
  console.log('manager@libraryhub.ng    / Admin1234!');
  console.log('── Librarians ──');
  console.log('librarian@libraryhub.ng  / Admin1234!');
  console.log('librarian2@libraryhub.ng / Admin1234!');
  console.log('librarian3@libraryhub.ng / Admin1234!');
  console.log('── Patrons ──');
  console.log('patron@libraryhub.ng     / Patron1234!');
  console.log('emeka@libraryhub.ng      / Patron1234!');
  console.log('amaka@libraryhub.ng      / Patron1234! (has fine)');
  console.log('tunde@libraryhub.ng      / Patron1234!');
  console.log('chisom@libraryhub.ng     / Patron1234!');
}

if (require.main === module) {
  seed().then(() => mongoose.disconnect()).catch(console.error);
}
